### PR TITLE
Some URL handling bug fixes

### PR DESCRIPTION
**Pull request by johniez**
* URL cleaner now removes doubled slashes, leading/trailing slashes (which was not handled well by the system)
 * URL validation checks for system registred URL and restricts creation of page names containing first url part same as system one
 * added URL cleanup into page move, where it was missing (allowing to create unsanitized urls)

### CODE REVIEW

**Comment by johniez** [comment]
The second commit fixes validation for new url names. Validation was checking page name before url_cleanup action (which may for example change space to underscore). Names with space was never found, event if the page already exists with name created after url cleanup.

I'm not sure if Windows wiki page handling is now correct, as slashes are transformed from backslashes... But probably it should be correct, because cleanup is made before page creation.

**Comment by alexanderjulo** [comment]
So I am currently adding appveyor support to enable automatic testing on windows and if you add some tests (I already have some, but probably not enough) we should be able to see whether it will work everywhere. 🙂

**Comment by johniez** [comment]
Ok, I will start submitting PRs with tests included. :-)
Anyway I have a non trivial merge to solve, here... :)

**Comment by alexanderjulo** [comment]
Closing this PR due to lack of activity.

**Pull request closed without merging**
